Code2Seq
JetBrains-Research/contrastive-learning-framework pull request #3
Opened 2021-03-12 09:18 UTC by maximzubkov

Add `code2seq` model and refactor `DataModules`

2021-03-12 09:50 UTC, maximzubkov commented
In both PR tests are not passed due to the problems in `torchvision`, the problem is discussed in the [issue](https://github.com/pytorch/vision/issues/3554)

2021-03-13 09:22 UTC, maximzubkov commented
I decided to switch from the `MNIST` dataset to `CIFAR10`

2021-03-15 17:44 UTC, SpirinEgor requested changes
Have few questions

2021-03-15 17:44 UTC, SpirinEgor commented on dataset/data_modules/text_data_module.py
> +    @abstractmethod
It is strange that you mark a method as abstract and then immediately implement it. Maybe it's better to remove this decorator?

2021-03-16 10:42 UTC, SpirinEgor approved these changes

2021-03-16 10:45 UTC, merged